language: go

notifications:
  email: false

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
  - go get github.com/golang/lint/golint
  - go get github.com/fzipp/gocyclo

script:
  - gocyclo -over 19 $GO_FILES
  - make test
